---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogify-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blogify
  template:
    metadata:
      labels:
        app: blogify
    spec:
      containers:
        - name: blogify
          image: ashuto91/blogify:latest
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
